# vim: ft=yaml.docker-compose
---
name: open-webui

include:
  - ext/docker-compose-snippets/tailscale-caddy.yaml
  - ext/docker-compose-snippets/simple-reverse-proxy.yaml
  - ext/docker-compose-snippets/volume-backup-schedules.yaml

services:
  openwebui:
    image: ghcr.io/rahulsalvi/open-webui:latest
    environment:
      WEBUI_URL: https://${COMPOSE_PROJECT_NAME}.ipn.rahulsalvi.com
      PORT: 8080
      ENABLE_LOGIN_FORM: false
      ENABLE_OAUTH_SIGNUP: true
      OAUTH_PROVIDER_NAME: Pocket ID
      OPENID_PROVIDER_URL: https://pocket-id.ipn.rahulsalvi.com/.well-known/openid-configuration
      OAUTH_CLIENT_ID: $OIDC_CLIENT_ID
      OAUTH_CLIENT_SECRET: $OIDC_CLIENT_SECRET
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    extends:
      file: ext/docker-compose-snippets/tailscale-app-base.yaml
      service: tailscale-app-base

  backup:
    volumes:
      - open-webui:/backup:ro
    extends:
      file: ext/docker-compose-snippets/volume-backup.yaml
      service: aws-backup-infrequent

volumes:
  open-webui:
